language: java
sudo: false
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.ivy2
install: true
script:
- ./activator clean compile checkstyle findbugs test stage
after_success:
- if [ \( -n "${TRAVIS_TAG}" \) -a  "${TRAVIS_PULL_REQUEST}" = "false" ]; then ./activator publish; fi;
