// Generated by typings
// Source: app/assets/javascripts/libs/d3/d3gauge.d.ts
declare class Gauge {
    constructor(id: string, options: any);
    render(): void;
    redraw(value: number, duration?: number): void;
}
